version: "3.8"

services:
    # db:
    #     image: postgres
    #     environment:
    #         - POSTGRES_DB=postgres
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    web:
        container_name: web
        build: ./src
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - ./src:/code
        ports:
            - "80:80"
        depends_on:
            - db
    # ng:
    #     container_name: ng
    #     build: angular
    #     ports: 
    #         - "8080:80"

# volumes:
#     postgres_data: